Cowards/OnlyArts

- src/main/java/com/cowards/onlyarts/services/ArtworkDAO.java
> feat artwork

- src/main/java/com/cowards/onlyarts/resources/v2/Report.java
- src/main/java/com/cowards/onlyarts/services/NotificationDAO.java
- src/main/java/com/cowards/onlyarts/services/ReportDAO.java
> feat Report

- src/main/java/com/cowards/onlyarts/resources/v4/Favor.java
- src/main/java/com/cowards/onlyarts/services/FavorDAO.java
> feat favor

- src/main/java/com/cowards/onlyarts/resources/v4/Follow.java
- src/main/java/com/cowards/onlyarts/services/FollowDAO.java
> feat follow

- src/main/java/com/cowards/onlyarts/resources/v3/Dashboard.java
- src/main/java/com/cowards/onlyarts/services/UserDAO.java
SWP-63 #back-end completed
SWP-62 #back-end completed
SWP-61 #back-end completed
SWP-60 #back-end completed
SWP-59 #back-end completed
> feat dashboard

- src/main/java/com/cowards/onlyarts/resources/v3/Cart.java
- src/main/java/com/cowards/onlyarts/resources/v3/Order.java
- src/main/java/com/cowards/onlyarts/services/CartDAO.java
- src/main/java/com/cowards/onlyarts/services/OrderDAO.java
- src/main/java/com/cowards/onlyarts/services/OrderDetailDAO.java
SWP-57 #back-end completed
SWP-56 #back-end completed
> feat order

- src/main/java/com/cowards/onlyarts/resources/v1/Password.java
- src/main/java/com/cowards/onlyarts/services/UserDAO.java
SWP-42 #back-end completed
SWP-41 #back-end completed
> feat password

- src/main/java/com/cowards/onlyarts/resources/v1/Image.java
- src/main/java/com/cowards/onlyarts/services/ImageDAO.java
> feat image

- src/main/java/com/cowards/onlyarts/resources/v3/Artwork.java
- src/main/java/com/cowards/onlyarts/resources/v3/Dashboard.java
- src/main/java/com/cowards/onlyarts/resources/v3/Order.java
- src/main/java/com/cowards/onlyarts/resources/v3/User.java
- src/main/java/com/cowards/onlyarts/services/ArtworkDAO.java
- src/main/java/com/cowards/onlyarts/services/OrderDAO.java
- src/main/java/com/cowards/onlyarts/services/UserDAO.java
Artwork
ArtworkDAO
Dashboard
Order
OrderDAO
User
UserDAO
> feat load api

- src/main/java/com/cowards/onlyarts/services/RequestDAO.java
- src/main/java/com/cowards/onlyarts/services/ResponseDAO.java
remove set time when creating request and response
> fix requestDAO and responseDAO

- src/main/java/com/cowards/onlyarts/resources/v1/Authentication.java
Add javadocs to Authentication.java
> refactor: add javadocs to Authentication.java file

- src/main/java/com/cowards/onlyarts/resources/v1/Image.java
Add javadocs to Image.java file
> refactor: add javadocs to Image.java file

- src/main/java/com/cowards/onlyarts/resources/v1/Password.java
Add javadocs to Password.java file
> refactor: add javadocs to Password.java file

- src/main/java/com/cowards/onlyarts/resources/v2/Comment.java
Add javadocs to Comment.java file in v2 package
> refactor: add javadocs to Comment.java file

- src/main/java/com/cowards/onlyarts/resources/v2/Favor.java
Add javadocs to Favor.java file in v2 package
> refactor: add javadocs to Favor.java file

- src/main/java/com/cowards/onlyarts/resources/v2/Reaction.java
Add javadocs to Reaction.java file in v2 package
> refactor: add javadocs to Reaction.java file

- src/main/java/com/cowards/onlyarts/resources/v2/Report.java
Add javadocs to Report.java file in v2 package
> refactor: add javadocs to Report.java file

- src/main/java/com/cowards/onlyarts/resources/v3/Artwork.java
Add javadocs to Artwork.java file in v3 package
> refactor: add javadocs to Artwork.java file

- src/main/java/com/cowards/onlyarts/resources/v3/Cart.java
Add javadocs to Cart.java file
> refactor: add javadocs to Cart.java file

- src/main/java/com/cowards/onlyarts/resources/v3/Order.java
Add javadocs to Order.java file
> refactor: add javadocs to Order.java file

- src/main/java/com/cowards/onlyarts/resources/v4/Follow.java
Add javadocs to Follow.java file
> refactor: add javadocs to Follow.java file

- src/main/java/com/cowards/onlyarts/resources/v4/Request.java
Add javadocs to Request.java file
> refactor: add javadocs to Request.java file

- src/main/java/com/cowards/onlyarts/resources/v4/ResponseAPI.java
Add javadocs to ResponseAPI.java file
> refactor: add javadocs to ResponseAPI.java file

- src/main/java/com/cowards/onlyarts/resources/v4/User.java
Add javadocs to User.java file in v4 package
> refactor: add javadocs to User.java file

- src/main/java/com/cowards/onlyarts/services/CategoryDAO.java
> feat load category

- src/main/java/com/cowards/onlyarts/resources/v3/Cart.java
- src/main/java/com/cowards/onlyarts/resources/v3/Order.java
- src/main/java/com/cowards/onlyarts/resources/v3/OrderDetail.java
- src/main/java/com/cowards/onlyarts/services/CartDAO.java
- src/main/java/com/cowards/onlyarts/services/OrderDAO.java
- src/main/java/com/cowards/onlyarts/services/OrderDetailDAO.java
Cart, Order, OrderDetail, CartDAO, OrderDAO, OrderDetailDAO
> feat load order
